### ISSUE TITLE
performance.py not completed 

### ISSUE THREAD

**Issue by Secondgrade** [Housiadas/forecasting-energy-consumption-LSTM#2]
Hi, I am using your seq2seq to build models, and which is pretty clear and easy-understanding. Really thanks for your efforts. But when I try to evaluate my model, I found out that there are no completed file for prediction or evaluate the model. So, if you are ok to publish these files, I would be really appreciate it.

**Comment by Housiadas** [comment]
Hi, i was running the code in google colab, which uses python jupyter notebook. So, after the training of the model I had the ability to use the performance.py, because the model and the trained variables were saved in the project's environment.
Sorry my bad i should have post it in the ReadMe file.

**Comment by Secondgrade** [comment]
Oh, that make sense. Thanks for your reply.
